sources:
  - domain: https://www.reuters.com/finance
    limit: 40
    language: en

  - domain: https://www.cnbc.com/finance/
    limit: 40
    language: en

  - domain: https://finance.yahoo.com
    limit: 40
    language: en

  - domain: https://www.marketwatch.com/latest-news
    limit: 40
    language: en

  - domain: https://www.investing.com/news
    limit: 40
    language: en

  - domain: https://www.nasdaq.com/news-and-insights
    limit: 40
    language: en

  # Tech x finance crossover (often parseable)
  - domain: https://www.theverge.com/money
    limit: 25
    language: en
