# Curated ticker metadata used for analytics enrichment
# Extend this list as you cover more equities.
tickers:
  AAPL:
    name: Apple Inc.
    sector: Information Technology
  MSFT:
    name: Microsoft Corporation
    sector: Information Technology
  GOOGL:
    name: Alphabet Inc.
    sector: Communication Services
  AMZN:
    name: Amazon.com, Inc.
    sector: Consumer Discretionary
  NVDA:
    name: NVIDIA Corporation
    sector: Information Technology
  TSLA:
    name: Tesla, Inc.
    sector: Consumer Discretionary
  META:
    name: Meta Platforms, Inc.
    sector: Communication Services
  JPM:
    name: JPMorgan Chase & Co.
    sector: Financials
  BAC:
    name: Bank of America Corporation
    sector: Financials
  XOM:
    name: Exxon Mobil Corporation
    sector: Energy
